# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vector_service_pb2 as vector__service__pb2


class VectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendVector = channel.stream_stream(
                '/VectorService/SendVector',
                request_serializer=vector__service__pb2.TextRequest.SerializeToString,
                response_deserializer=vector__service__pb2.VectorResponse.FromString,
                )


class VectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendVector(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendVector': grpc.stream_stream_rpc_method_handler(
                    servicer.SendVector,
                    request_deserializer=vector__service__pb2.TextRequest.FromString,
                    response_serializer=vector__service__pb2.VectorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'VectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendVector(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/VectorService/SendVector',
            vector__service__pb2.TextRequest.SerializeToString,
            vector__service__pb2.VectorResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
